telegram:
  api_id: 26414050        # e.g., 1234567
  api_hash: 778a91fbc6f67c3c9a8cbc9a626eab9f     # e.g., "a1b2c3d4e5f6g7h8i9j0k"
  phone: +251931891020                    # e.g., "+251912345678"

channels:
  - "@shageronlinestore"               # Example channel
  - "@ZemenExpress"
  - "@nevacomputer"
  - "@meneshayeofficial"
  - "@ethio_brand_collection"

models:
  - xlm-roberta-base
  - bert-tiny-amharic

paths:
  raw_data: ./data/raw/
  processed_data: ./data/processed/
  labeled_data: ./data/labeled/
  model_output: ./models/